from pprint import pprint

env = Environment(
    CPPFLAGS = ['-Wall', '-Werror'],
    NAME = '$ARCH-$MODE',
)
env.Tool('variantgen', toolpath = ['../../scons_tools'])
cg = env.VariantGen()

# Mode
vs_mode = cg.AddVariantSet('mode')

v_release = vs_mode.AddVariant(MODE='release')
v_release.Append(
    CPPDEFINES = ['NDEBUG'],
    CPPFLAGS = ['-O3'],
)

v_debug = vs_mode.AddVariant(MODE='debug')
v_debug.Append(
    CPPDEFINES = ['DEBUG'],
)


# Architecture
vs_arch = cg.AddVariantSet('arch')

vs_arch.AddVariant(ARCH='x86')
vs_arch.AddVariant(ARCH='arm')



cg.Dump()

for env in cg.GenerateEnvironments():
    print 'Environment:', env.subst('$NAME')
